### ISSUE TITLE
文档不见啦文档不见啦

### ISSUE THREAD

**Issue by fengdongfei** [weex-ui-team/weex-ui#476]
文档不见啦文档不见啦文档不见啦文档不见啦文档不见啦文档不见啦文档不见啦文档不见啦文档不见啦文档不见啦文档不见啦文档不见啦文档不见啦文档不见啦文档不见啦文档不见啦文档不见啦文档不见啦文档不见啦文档不见啦文档不见啦文档不见啦文档不见啦文档不见啦文档不见啦文档不见啦文档不见啦文档不见啦文档不见啦文档不见啦文档不见啦文档不见啦文档不见啦文档不见啦文档不见啦文档不见啦文档不见啦文档不见啦

**Comment by tw93** [comment]
见上一个issue https://weex-ui-team.github.io/weex-ui/
